# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Docs
tagline:          "We're in documentation"
url:              http://werein.cz

github:
  repo:           https://github.com/werein